name: Build

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6
    
    - name: Install dependencies
      run: dotnet restore RallySimulator.sln

    - name: Build
      run: dotnet build RallySimulator.sln -c Release --no-restore